#pragma once

#define VENDOR_ID 0xFEED
#define PRODUCT_ID 0x6060
#define DEVICE_VER 0x0001

#define MATRIX_ROWS 1
#define MATRIX_COLS 4

#define MATRIX_ROW_PINS { D0 }
#define MATRIX_COL_PINS { D2, D3, C6, D4 }
#define DIODE_DIRECTION COL2ROW

// RGB Matrix
#define RGB_DI_PIN D1
#define DRIVER_LED_TOTAL 4
#define RGB_MATRIX_LED_COUNT 4
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 200

#define RGB_DISABLE_WHEN_USB_SUSPENDED true
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR

// Layer count
#define LAYER_STATE_8BIT

#define USB_POLLING_INTERVAL_MS 1
#define DYNAMIC_KEYMAP_LAYER_COUNT 3